name: Build and deploy frontend
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build frontend
    runs-on: ubuntu-latest
    env:
          VUE_APP_TESTE_ENV: ${{secrets.VUE_APP_TESTE_ENV_PROD}}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      
      - name: Cache npm modules
        uses: actions/cache@v2
        env:
          cache-name: cache-npm
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
      
      - name: Install yarn
        run: npm i -g yarn

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: |
          if [ ! -d "./node_modules" ]; then
            yarn
          fi
      
      - name: Cache dist
        uses: actions/cache@v2
        env:
          cache-name: cache-dist
        with:
          path: '**/dist'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/src') }}
        
      - name: Build and add dist
        run: |
          if [ ! -d "./dist" ]; then
            yarn build
            git add dist/ --force
            git config --global user.email "breno_douglas@hotmail.com"
            git config --global user.name "Breno Douglas"
            git commit -m "Add dist folder for push to heroku"
          fi

      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: "breninho94@gmail.com"
